version: '3'
services:
  my-python-service:
    build:
      context: .
      dockerfile: Dockerfile
  my-csharp-service:
    build: 
      context: .
      dockerfile: Dockerfile.csharp
    volumes:
      - .:/app
  my-python-service2:
    build:
      context: .
      dockerfile: Dockerfile2
  my-iso-radon-service:
    build:
      context: .
      dockerfile: RadonDockerfile