version: '3'
services:
  my-python-service:
    build:
      context: .
      dockerfile: Dockerfile
  my-csharp-service:
    build: 
      context: .
      dockerfile: Dockerfile.csharp
    volumes:
      - ${WORKSPACE_PATH}:/app
  my-python-service2:
    build:
      context: .
      dockerfile: Dockerfile2
  my-iso-radon-service:
    build:
      context: .
      dockerfile: RadonDockerfile
    tmpfs:
      - /app
  my-iso-cpd-service:
    build:
      context: .
      dockerfile: CpdDockerfile
    tmpfs:
      - /app
  my-iso-bandit-service:
    build:
      context: .
      dockerfile: BanditDockerfile
    tmpfs:
      - /app